---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-nginx-ingress
  namespace: test-ngnx
spec:
  ingressClassName: "nginx"
  tls:
   - hosts:
        - "homepage.local."
  rules:
    - host: "homepage.local"
      http:
        paths:
         - path: /
           pathType: Prefix
           backend:
             service:
               name: nginx-service
               port:
                 number: 80 
