---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: test-ngnx
  labels:
    app: nginx-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: {{ .Release.Name }}
